### ISSUE TITLE
React warnings

### ISSUE THREAD

**Issue by ivan-kleshnin** [ivan-kleshnin/unredux#11]
React raises a warning for fields with `value` but without `onChange`. It's not applicable for our architecture. The current workaround is:

```
<input type="text" name="filter.tag" value={index.filter.tag} onChange={R.id}/> Tag
```

Need to suppress this warning in a single place.

---

Consider the following.

```
// Should suppress DevTool warning since React 16.1.0
// plugins: [
//   new Webpack.DefinePlugin({
//     "__REACT_DEVTOOLS_GLOBAL_HOOK__": "({ isDisabled: true })"
//   }),
// ]
```

React 16.1.1 is released.

**Comment by scabbiaza** [comment]
1. Ongoing discussion -- https://github.com/facebook/react/issues/1118

2. React Tools warning

After some research found the same solution.
This is funny:
https://github.com/facebook/react/issues/3877#issuecomment-333779785


3. Also, this can be useful, new feature in React 16.1.0
`Add a new suppressHydrationWarning attribute for intentional client/server text mismatches. `

<img width="424" alt="screen shot 2017-11-29 at 19 58 47" src="https://user-images.githubusercontent.com/2734464/33390830-c5ee8892-d53f-11e7-8f6e-2754f1d7d853.png">

**Comment by ivan-kleshnin** [comment]
When you're starting to add attributes like `suppressHydrationWarning` – it's a bad sign. Warnings should be 100% relevant or they should be removed.

**Comment by scabbiaza** [comment]
Update about the warning
```warning.js:33 Warning: Expected server HTML to contain a matching <div> in <div>.```

Without SSR we should not use `hydrate` method, or this warning will be shown

**Comment by ivan-kleshnin** [comment]
Done, as much as it's possible right now.
