### ISSUE TITLE
Fix a bug with scroll

### ISSUE THREAD

**Issue by ivan-kleshnin** [ivan-kleshnin/unredux#19]
`elem.scrollIntoView()` 
* works for a "click on a link" event
* doesn't work for a "back/forward in history" event

https://github.com/ivan-kleshnin/unredux/tree/scroll-bug

Check `vendors/framework.js`, `navigateTo$` and `navigateHistory$` streams.

**Comment by scabbiaza** [comment]
We can discuss it more on the call, but I think that by clicking on back/forward in the history,
a user should be scrolled not to the section by hash, but to the place on the screen that he/she has left. 
Because this is how browser works:
https://stackoverflow.com/questions/27046851/browser-back-button-does-not-work-for-anchor-links

**Comment by scabbiaza** [comment]
This is a default browser's behavior:
https://stackoverflow.com/questions/27046851/browser-back-button-does-not-work-for-anchor-links

The solution can be:
```history.scrollRestoration = "manual"```

More info about it:
https://developers.google.com/web/updates/2015/09/history-api-scroll-restoration

We can use polyfill, but it's not a small lib (780Kb) and latest Chrome and FF have a support for `history.scrollRestoration`:
https://github.com/bfred-it/scroll-restoration-polyfill

**Comment by ivan-kleshnin** [comment]
Decided not to mess with the default behavior which is fine.
